//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.UserInfoes = new HashSet<UserInfo>();
        }
    
        public int DistrictId { get; set; }
        public string Name { get; set; }
        public int DivitionId { get; set; }
    



        public virtual Divition Divition { get; set; }
        public virtual ICollection<UserInfo> UserInfoes { get; set; }
    }
}
