//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserId { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public int Mobile { get; set; }
        public int GenderId { get; set; }
        public int DivitionId { get; set; }
        public int DistrictId { get; set; }
        public string PresentAddress { get; set; }
        public string LastEducationalQulification { get; set; }
        public string Occupation { get; set; }
        public System.DateTime DateOFBirth { get; set; }

        public virtual District District { get; set; }
        public virtual Divition Divition { get; set; }
    }
}
